#
# /etc/pacman.conf — used only at ISO BUILD TIME by mkarchiso to install
# packages into the airootfs. The runtime pacman.conf shipped to the live
# system is at airootfs/etc/pacman.conf.
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 8
DownloadUser = alpm

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
